# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  fe:
    build: ./front
    image: rujrawee11/fe:latest
    ports: 
      - 8088:80
    links:
      - be
      - mongo_db
      - mongo_express
    networks:
      - front-tier
    

  be:
    build: ./express-mongodb-api
    image: rujrawee11/be:latest
    ports: 
      - 3000:3000
    networks:
      - back-tier
    links:
      - mongo_dbs
      - mongo_express
  mongo_db:
    container_name: mongodb
    image: rujrawee11/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: myUserAdmin
    ports:
      - 27017:27017
    volumes: 
      - ./database-data:/data/db
            
  mongo_express:
    container_name: mongo-express
    image: rujrawee11/mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myUserAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: myUserAdmin
      ME_CONFIG_MONGODB_SERVER: mongodb
            



networks:
  front-tier:
  back-tier:
