# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  fe:
    build: ./front
    image: rujrawee11/fe:1.0
    ports: 
      - 5000:80



  api:
      build: ./express-mongodb-api
      ports:
          - 8088:80
      environment:
        PORT: 80
        MONGODB_URI: mongodb://myUserAdmin:myUserAdmin@localhost:27017
        DB_NAME: myUserAdmin
        NAME: myUserAdmin
  



