# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  fe:
    build: ./front
    image: rujrawee11/fe:latest
    ports: 
      - 3000:80
    links:
      - be
    networks:
      - front-tier
    
  mongo_db:
        container_name: db_container
        image: mongo:lastest
        restart: always
        ports:
            - 2717:27017
        volumes: 
            - mongo_db:/data/db
  api:
        build: ./express-mongodb-api
        ports:
          - 5001:80
        volumes:
          - .:/usr/src/app
        environment:
           PORT: 3000
           MONGODB_URI: mongodb://myUserAdmin:myUserAdmin@localhost:27017
           DB_NAME: myUserAdmin
           NAME: myUserAdmin
        depends_on:
        - mongo_db
  volumes:
        mongo_db:

networks:
  front-tier:
  back-tier:
  
