version: '3'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: rujrawee11/my-backend_image:lastest
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: rujrawee11/my-frontend_image:lastest
