# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  fe:
    build: ./front
    image: rujrawee11/fe:latest
    ports: 
      - 3000:80
    links:
      - be
    networks:
      - front-tier
    
  mongo_db:
        container_name: db_container
        image: mongo:lastest
        restart: always
        ports:
            - 2717:27017
        volumes: 
            - mongo_db:/data/db
 app:
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - mongo_db
    environment:
      NODE_ENV: development
    ports:
      - 5001:80
    command: npm run dev
volumes:
  dependencies:
