# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  fe:
    build: ./front
    image: rujrawee11/fe:latest
    ports: 
      - 8088:8088
    links:
      - be
    networks:
      - front-tier
    

  be:
    build: ./express-mongodb-api
    image: rujrawee11/be:latest
    ports: 
      - 3000:80
    networks:
      - back-tier
  
networks:
  front-tier:
  back-tier:
